### ISSUE TITLE
Save last few request/response so when client opens up it has some history

### ISSUE THREAD

**Issue by deomitrus** [deomitrus/utini#14]
When a client loads up, it would be nice to have some history of previous requests/responses that happened in the recent timeframe. Just, you know... so it's not all empty and what not

**Comment by goavn** [comment]
Related to #8 - should use same storage engine

**Comment by deomitrus** [comment]
Capped collections, expiring data, how to prune old data?

**Comment by deomitrus** [comment]
This feature request is not desired right now. Plus, this functionality could potentially be met with IndexedDB.
