### ISSUE TITLE
Figure out where to store request and response data

### ISSUE THREAD

**Issue by deomitrus** [deomitrus/utini#8]
Presumably, when you proxy stuff, it would be nice to have detailed information about requests and responses, like headers, body, request time, etc.

So where should this data be stored?

- local storage: could be very noisy, especially if only 1% of the data is actually used. if running in electron, then any storage option would be local anyways
- pouchdb: flatfile couchDB thingy. easy to work with
- mongodb: yeah, but uses a shit ton of memory and how difficult would it be to setup a standalone?
- redis: again, all in memory... users will be all like OH WTF WHERE IS MAH MEMORY
- /dev/null: it's webscale!

**Comment by deomitrus** [comment]
pouchdb with indexedDB/webSQL or NeDB?

**Comment by deomitrus** [comment]
PouchDB is kinda cool. Could use server-side leveldown storage and also indexedDB with the same API. Problem is that compiling leveldown is a PITA - has to be done for each dist platform.

https://github.com/nolanlawson/pouchdb-nw
https://github.com/nwjs/nw.js/wiki/Save-persistent-data-in-app

**Comment by goavn** [comment]
Can't build leveldown in CI on multiple environments - OSX, Windows, etc.

**Comment by deomitrus** [comment]
Trying PouchDB. Still unsure about in-memory vs file based. This could get out of control quickly.

**Comment by deomitrus** [comment]
PouchDB in browser with IndexedDB for all metadata. Right now we are not going to store body data. That will be stored server-side. Body data does not get persisted. Express makes it difficult to get raw body data out.

**Comment by deomitrus** [comment]
Exploratory task is completed. Please see issue #25 for implementation.
