### ISSUE TITLE
Use manual list of babel plugins until v8 4.9, at which point most can go away

### ISSUE THREAD

**Issue by goavn** [deomitrus/utini#93]
v8 4.9 has > 90% es6 support
electron already has chrome 49
waiting on node to catch up... node y u so slow?

use manual babel plugins:
- from node5 preset
- async/await transform

DO NOT USE THE MODULE ONES because it's all derp and whatever

template here: https://github.com/leebenson/babel-preset-node5

**Comment by deomitrus** [comment]
May not need this, as using fix module exports presets seems to make everything okay.

Once node v8 4.9 is released, the number of plugins needed may be very small.

This task would then be to verify that the minimal number of plugins are active in the build pipeline.

**Comment by goavn** [comment]
This task should not be part of alpha 1. Track V8 4.9 or 5.0 release in Node and assign this issue to be completed by that time.

**Comment by deomitrus** [comment]
good now
